# Generated by Django 5.2.7 on 2025-10-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notebook_version_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='notebook',
            new_name='notebook_id',
        ),
        migrations.AddField(
            model_name='version',
            name='page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='notebooks.page'),
        ),
    ]
