# Generated by Django 5.2.7 on 2025-10-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_rename_notebook_page_notebook_id_version_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='previous_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_versions', to='notebooks.version'),
        ),
    ]
