# Generated by Django 5.2.7 on 2025-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_alter_version_previous_version_draft_post_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='merge_threshold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='toss_threshold',
            field=models.IntegerField(null=True),
        ),
    ]
