# Generated by Django 5.2.7 on 2025-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_notebook_merge_threshold_notebook_toss_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
