# Generated by Django 5.2.7 on 2025-10-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0007_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='agree',
        ),
    ]
