# Generated by Django 5.2.7 on 2025-10-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0008_remove_vote_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='toss_threshold',
        ),
    ]
