# Generated by Django 5.2.7 on 2025-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0009_remove_notebook_toss_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='version',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
